package io.github.adrian0511.prompt_link.dto;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * The body returned by {@code POST /chat/completions}.
 *
 * <p>The API may return several alternative answers; this library always uses the first one. Careful:
 * the list can come back empty even with a 200, so it cannot be indexed blindly.
 *
 * <p>Unknown properties ({@code id}, {@code usage}, {@code model}…) are ignored, since only the
 * generated text matters here. That is explicit on purpose: without the annotation, deserialization
 * would depend on the application not having enabled {@code FAIL_ON_UNKNOWN_PROPERTIES} on its
 * ObjectMapper, and on OpenRouter never adding a field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class OpenRouterResponse {

    private List<Choice> choices;

    /** One of the alternative answers generated by the model. */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Choice {

        private Message message;

        public Message getMessage() {
            return message;
        }

        public void setMessage(Message message) {
            this.message = message;
        }

    }

    public List<Choice> getChoices() {
        return choices;
    }

    public void setChoices(List<Choice> choices) {
        this.choices = choices;
    }

}
